### PR TITLE
feat: improve test assertions

### PR DESCRIPTION
**Pull request by laggingreflex**
(this is on top of #26)

When a test fails, it shows an output like this, which is hard to look at:

```
  1) c8
       merges reports from subprocesses together:
     AssertionError: expected ',first\n\nsecond\n\n--------------------|----------|----------|----------|----------|-------------------|\nFile
             |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |\n--------------------|----------|----------|----------|----------|----------
     ---------|\nAll files           |    94.12 |    73.08 |        0 |    94.12 |                   |\n bin                |    83.72 |    57.14 |      10
```

This commit tries to improve the error message by using snapshot testing.

### CODE REVIEW

**Comment by laggingreflex** [comment]
@JaKXz Good idea, thanks! Updated. 

One test that uses `should.match(regex)` assertion couldn't be used with snapshot though.

**Comment by bcoe** [comment]
@laggingreflex @JaKXz I like this too; shall we land this instead of my `clean` branch? looks like you already rebased.

**Comment by bcoe** [comment]
@laggingreflex oh, one suggestion. Can we add an npm command that takes the snapshots?

**Comment by laggingreflex** [comment]
Sure, added `test:snap`

**Pull request merged**
