### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
##### Checklist

- [x] `npm test`, tests passing
- [ ] `npm run test:snap` (to update the snapshot)

TODO:

- [ ] figure out the Node.js 10 failure (on my dev branch this is passing: https://github.com/XhmikosR/c8/runs/5245909188?check_suite_focus=true so maybe a test needs to be adapted?)

Closes #356 along the way.

### CODE REVIEW

**Comment by bcoe** [comment]
It seems odd to me that this would change snapshot output significantly, do you know which dependency update is doing this?

**Comment by XhmikosR** [comment]
Unfortunately, I don't know which dependency exactly is causing this.

**Comment by XhmikosR** [comment]
Could you try updating the Node.js 10 snapshot? It might be just it's behind.

**Comment by bcoe** [comment]
see: https://github.com/bcoe/c8/issues/385

I've created a separate PR that updates deps.

**Comment by XhmikosR** [comment]
So, this leaves `v8-to-istanbul` which could have caused the issue.

**Pull request closed without merging**
